### ISSUE TITLE
Refatoração do arquivo Program.cs

### ISSUE THREAD

**Issue by josineudo-arruda** [josineudo-arruda/LabManager#1]
Atualmente o código do programa está organizado em um único arquivo, com muitas responsabilidades: roteamento com base no `args`, conexão com o banco de dados, criação de tabelas, consultas SQL e textos que retornam como resposta.

Uma possível solução seria criar uma classe que é responsável por fazer o setup do banco de dados, outra classe que representa um Computador (id, ram, processador) e uma classe que abstrai o acesso a dados, com métodos para criar um novo computador e listar computadores cadastrados.

## Tarefas

- [x] Criar classe de setup do banco de dados
- [x] Implementar a classe Computer
- [x] Implementar a classe de acesso a dados para Computer

**Comment by jarvmds** [comment]
Belo código!
